/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ResumeImprovementSuggestion = IDL.Record({
  'strongAlternatives' : IDL.Vec(IDL.Text),
  'weakVerb' : IDL.Text,
});
export const JobRole = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'requiredSkills' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addResumeTemplate' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'getActionVerbSuggestions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, ResumeImprovementSuggestion))],
      ['query'],
    ),
  'getCertifications' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getJobRoles' : IDL.Func([], [IDL.Vec(JobRole)], ['query']),
  'getResumeTemplate' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getResumeTemplates' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ResumeImprovementSuggestion = IDL.Record({
    'strongAlternatives' : IDL.Vec(IDL.Text),
    'weakVerb' : IDL.Text,
  });
  const JobRole = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'requiredSkills' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addResumeTemplate' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'getActionVerbSuggestions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, ResumeImprovementSuggestion))],
        ['query'],
      ),
    'getCertifications' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getJobRoles' : IDL.Func([], [IDL.Vec(JobRole)], ['query']),
    'getResumeTemplate' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getResumeTemplates' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };